title: Vinita Jhakra # your name (or website title) here
logo: "/images/VKJ.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <br>Data Scientist with 6+ years experience in Robotic Process Automation and Master's degree in Data Science from City, University of London. Previously worked in Virgin Media o2 and Tata Consultancy Services<br>
  
  <a href="https://www.linkedin.com/in/vinita-kumari-jhakra-326665203?l">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

